fix: view post/page from WP admin
postlight/headless-wp-starter pull request #329
Opened 2022-02-07 17:48 UTC by royelkhoury

## Description:
The purpose of this PR is to enable view posts and pages from WP admin post/page list.
Refer to [this issue](https://github.com/postlight/headless-wp-starter/issues/186)

## GIFs
#### Before
![Screen Recording 2022-02-07 at 4 41 10 PM](https://user-images.githubusercontent.com/64750380/152843502-291f6489-329d-483a-bef2-496f55c95f6b.gif)

#### After
![Screen Recording 2022-02-07 at 4 39 30 PM](https://user-images.githubusercontent.com/64750380/152843526-5e7be36e-d9c1-459d-a72d-238f016bf627.gif)

2022-02-08 07:28 UTC, alexiakl requested changes
Thanks for picking this up Roy.
I requested few changes

2022-02-08 07:28 UTC, alexiakl commented on frontend/pages/preview.js
> +    let url = { query: { id, rev, type, status, wpnonce } };
url looks to be immutable, it should be a const

2022-02-08 07:28 UTC, alexiakl commented on frontend/pages/preview.js
> +    if (status === 'draft') {
spacing changes here needs to be reverted, they are introduced by a php linter

2022-02-08 07:28 UTC, alexiakl commented on frontend/pages/preview.js
> +      .then((res) => res.json())
same here. revert the parentheses changes please

2022-02-08 07:28 UTC, alexiakl commented on wordpress/wp-content/themes/postlight-headless-wp/inc/admin.php
> +add_filter( 'post_link', 'set_headless_preview_link' );
I need to check this closer - so I'll run the project, but it looks like you're setting the link of normal posts and pages as a preview link. No action needed here for now, but I gonna check few things

2022-02-08 09:27 UTC, royelkhoury commented
Thanks @alexiakl for the feedback, changes found in 4fac37e

2022-03-04 10:26 UTC, reemobeid17 commented on frontend/pages/preview.js
> +    return { url: { query } };
Have a look at the refactored code @royelkhoury @alexiakl

2022-03-04 12:07 UTC, alexiakl approved these changes

2022-03-10 10:40 UTC, merged